// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ayLJdrbmzqEWpRLgy_mG_TSN0A5Qu1w',
    appId: '1:824826771893:web:92a3612efa074ef00301fc',
    messagingSenderId: '824826771893',
    projectId: 'my-wallpaper-apps-36258',
    authDomain: 'my-wallpaper-apps-36258.firebaseapp.com',
    storageBucket: 'my-wallpaper-apps-36258.appspot.com',
    measurementId: 'G-1NM7SPES2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmFmT6iWIKVC8rZl5nj-KzTwdn_kfSfs',
    appId: '1:824826771893:android:bb8c2d35c2164f810301fc',
    messagingSenderId: '824826771893',
    projectId: 'my-wallpaper-apps-36258',
    storageBucket: 'my-wallpaper-apps-36258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALez1nfe8rE0wKP7iBlMutta-TVX73lFs',
    appId: '1:824826771893:ios:d2c8a1510bd8be000301fc',
    messagingSenderId: '824826771893',
    projectId: 'my-wallpaper-apps-36258',
    storageBucket: 'my-wallpaper-apps-36258.appspot.com',
    iosBundleId: 'com.example.myWallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALez1nfe8rE0wKP7iBlMutta-TVX73lFs',
    appId: '1:824826771893:ios:d2c8a1510bd8be000301fc',
    messagingSenderId: '824826771893',
    projectId: 'my-wallpaper-apps-36258',
    storageBucket: 'my-wallpaper-apps-36258.appspot.com',
    iosBundleId: 'com.example.myWallpaperApp',
  );
}
